name: boombox
main: com.cospox.boombox.Main
version: 0.2
api-version: 1.15
commands:
  stopgame:
    description: Stops and resets the game
    usage: /stopgame
    permission: boombox.stop
    permission-message: You don't have <permission>
  pausegame:
    description: Pauses the game
    usage: /pausegame
    permission: boombox.pause
    permission-message: You don't have <permission>
  startgame:
    description: Re-starts a paused or reset game
    usage: /startgame
    permission: boombox.start
    permission-message: You don't have <permission>

  onteam:
    description: Used to assign yourself to a team
    usage: /onteam red|blue
    permission: boombox.team
    permission-message: You don't have <permission>

